create table cards
(
multiverseid	integer			COMMENT="The multiverseid of the card on Wizard's Gatherer web page.",
layout      	varchar(255)	COMMENT="The card layout. Possible values: normal, split, flip, double-faced, token, plane, scheme, phenomenon, leveler, vanguard",
name        	varchar(255)	COMMENT="The card name. For split, double-faced and flip cards, just the name of one side of the card. Basically each 'sub-card' has it's own record.",
names       	varchar(255)	COMMENT="Only used for split, flip and dual cards. Will contain all the names on this card, front or back.",
manaCost    	varchar(255)	COMMENT="The mana cost of this card. Consists of one or more mana symbols.",
cmc         	numeric			COMMENT="Converted mana cost. Always a number. NOTE: cmc may have a decimal point as cards from unhinged may contain 'half mana' (such as 'Little Girl' with a cmc of 0.5)",
colors      	varchar(255)	COMMENT="The card colors. Usually this is derived from the casting cost, but some cards are special (like the back of dual sided cards and Ghostfire).",
type        	varchar(255)	COMMENT="The card type. This is the type you would see on the card if printed today. Note: The dash is a UTF8 'long dash' as per the MTG rules",
supertypes  	varchar(255)	COMMENT="The supertypes of the card. These appear to the far left of the card type. Example values: Basic, Legendary, Snow, World, Ongoing",
types       	varchar(255)	COMMENT="The types of the card. These appear to the left of the dash in a card type. Example values: Instant, Sorcery, Artifact, Creature, Enchantment, Land, Planeswalker",
subtypes    	varchar(255)	COMMENT="The subtypes of the card. These appear to the right of the dash in a card type. Usually each word is it's own subtype. Example values: Trap, Arcane, Equipment, Aura, Human, Rat, Squirrel, etc.",
rarity      	varchar(255)	COMMENT="The rarity of the card. Example values: Common, Uncommon, Rare, Mythic Rare, Special",
text        	varchar(255)	COMMENT="The text of the card. May contain mana symbols and other symbols.",
flavor      	varchar(255)	COMMENT="The flavor text of the card.",
artist      	varchar(255)	COMMENT="The artist of the card.",
number      	varchar(255)	COMMENT="The card number. This is printed at the bottom-center of the card in small text. This is a string, not an integer, because some cards have letters in their numbers.",
power       	varchar(255)	COMMENT="The power of the card. This is only present for creatures. This is a string, not an integer, because some cards have powers like: ?1+*'",
toughness   	varchar(255)	COMMENT="The toughness of the card. This is only present for creatures. This is a string, not an integer, because some cards have toughness like: '1+*'",
loyalty     	integer			COMMENT="The loyalty of the card. This is only present for planeswalkers.",
variations  	varchar(255)	COMMENT="If a card has alternate art (for example, 4 different Forests, or the 2 Brothers Yamazaki) then each other variation's multiverseid will be listed here, NOT including the current card's multiverseid.",
imageName   	varchar(255)	COMMENT="The mtgimage.com file name for this card. Note this is not the same format as CCGHQ. Seemtgimage.com for more details.",
watermark   	varchar(255)	COMMENT="The watermark on the card. Note: Split cards don't currently have this field set, despite having a watermark on each side of the split card.",
border      	varchar(255)	COMMENT="If the border for this specific card is DIFFERENT than the border specified in the top level set JSON, then it will be specified here. (Example: Unglued has silver borders, except for the lands which are black bordered)",
hand        	integer			COMMENT="Maximum hand size modifier. Only exists for Vanguard cards.",
life        	integer			COMMENT="Starting life total modifier. Only exists for Vanguard cards.",
rulings     	varchar(255)	COMMENT="The rulings for the card. An array of objects, each object having 'date' and 'text' keys.",
foreignNames	varchar(255)	COMMENT="Foreign language names for the card. An array of objects, each object having 'language' and 'name' keys. Not available for split, flip and double-faced cards.",
printings   	varchar(255)	COMMENT="The sets that this card was printed in. Note: This is a complete list of printings, so it may contain sets that are not available on MTG JSON.",
originalText	varchar(255)	COMMENT="The original text on the card at the time it was printed.",
originalType	varchar(255)	COMMENT="The original type on the card at the time it was printed.",
legalities  	varchar(255)	COMMENT="Which formats this card is legal, restricted or banned in. The object's keys are the format and the values are the legality.",
PRIMARY KEY (multiverseid)
)